No such file or directory creating .env file
## Description
Running the command `yarn buildpack create-env-file packages/venia-concept` to generate the .env file throws an error

## Expected
```
Successfully wrote a fresh configuration file to /Users/rdiaz/Sites/pwa-studio/packages/venia-concept/.env
```
## Actual
```
yarn run v1.16.0
$ /Users/jondoe/Sites/pwa-studio/node_modules/.bin/buildpack create-env-file packages/venia-concept
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/Users/jondoe/Sites/pwa-studio/packages/pwa-buildpack/dist/cli'
    at Object.readdirSync (fs.js:790:3)
    at requireDirectory (/Users/jondoe/Sites/pwa-studio/node_modules/require-directory/index.js:59:6)
    at Object.addDirectory (/Users/jondoe/Sites/pwa-studio/packages/pwa-buildpack/node_modules/yargs/lib/command.js:112:33)
    at Object.Yargs.self.commandDir (/Users/jondoe/Sites/pwa-studio/packages/pwa-buildpack/node_modules/yargs/yargs.js:364:13)
    at Object.<anonymous> (/Users/jondoe/Sites/pwa-studio/packages/pwa-buildpack/bin/buildpack:4:6)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```